version: '3.9'

services:
  postgres-social-network-1:
    container_name: postgres-social-network-1
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "social_network"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./postgres/psn1:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres-social-network-2:
    container_name: postgres-social-network-2
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "social_network"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./postgres/psn2:/var/lib/postgresql/data
    ports:
      - "25432:5432"

  postgres-social-network-3:
    container_name: postgres-social-network-3
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "social_network"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./postgres/psn3:/var/lib/postgresql/data
    ports:
      - "35432:5432"

#  social-network:
#    container_name: social-network-server
#    image: "feardude/social-network:0.0.1-SNAPSHOT"
#    environment:
#      JWT_KEY: $JWT_KEY
#      DB_HOST: $DB_HOST
#      DB_USERNAME: $DB_USERNAME
#      DB_PASSWORD: $DB_PASSWORD
#    ports:
#      - "8080:8080"
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
