spring:
  application:
    name: social-network
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
  data:
    redis:
      host: ${REDIS_HOST:localhost}

logging:
  level:
    root: info
    org.springframework.security: info
    ru.smax: ${LOGGING_LEVEL_RU_SMAX:info}

management:
  tracing:
    sampling:
      probability: 1.0
