max_wal_senders = 4

# по-умолчанию асинхронная потоковая репликация
wal_level = replica

# для кворумной репликации включить эти опции:
#synchronous_commit = on
#synchronous_standby_names = 'ANY 1 (psn2, psn3)'
